// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingApp;

namespace TrainingApp.Migrations
{
    [DbContext(typeof(TeamDbContext))]
    partial class TeamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrainingApp.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            Field = "A",
                            SessionDate = new DateTime(2022, 8, 2, 20, 31, 9, 590, DateTimeKind.Local).AddTicks(2308),
                            SessionEnd = "21:30",
                            SessionStart = "20:00"
                        },
                        new
                        {
                            MatchId = 2,
                            Field = "A",
                            SessionDate = new DateTime(2022, 8, 7, 20, 31, 9, 592, DateTimeKind.Local).AddTicks(2281),
                            SessionEnd = "21:30",
                            SessionStart = "20:00"
                        },
                        new
                        {
                            MatchId = 3,
                            Field = "A",
                            SessionDate = new DateTime(2022, 8, 12, 20, 31, 9, 592, DateTimeKind.Local).AddTicks(2281),
                            SessionEnd = "21:30",
                            SessionStart = "20:00"
                        });
                });

            modelBuilder.Entity("TrainingApp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            FirstName = "Thibaut",
                            LastName = "Courtois",
                            Position = "GK"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            FirstName = "Daniel",
                            LastName = "Carvajal",
                            Position = "RB"
                        },
                        new
                        {
                            Id = 3,
                            Age = 24,
                            FirstName = "Eder",
                            LastName = "Militao",
                            Position = "CB"
                        },
                        new
                        {
                            Id = 4,
                            Age = 30,
                            FirstName = "David",
                            LastName = "Alaba",
                            Position = "CB"
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            FirstName = "Jesus",
                            LastName = "Vallejo",
                            Position = "CB"
                        },
                        new
                        {
                            Id = 6,
                            Age = 32,
                            FirstName = "Nacho",
                            LastName = "Fernandez",
                            Position = "CB"
                        },
                        new
                        {
                            Id = 7,
                            Age = 31,
                            FirstName = "Eden",
                            LastName = "Hazard",
                            Position = "LW"
                        },
                        new
                        {
                            Id = 8,
                            Age = 32,
                            FirstName = "Toni",
                            LastName = "Kroos",
                            Position = "CM"
                        },
                        new
                        {
                            Id = 9,
                            Age = 34,
                            FirstName = "Karim",
                            LastName = "Benzema",
                            Position = "CF"
                        },
                        new
                        {
                            Id = 10,
                            Age = 36,
                            FirstName = "Luka",
                            LastName = "Modric",
                            Position = "CM"
                        },
                        new
                        {
                            Id = 11,
                            Age = 26,
                            FirstName = "Marco",
                            LastName = "Asensio",
                            Position = "RW"
                        },
                        new
                        {
                            Id = 13,
                            Age = 23,
                            FirstName = "Andriy",
                            LastName = "Lunin",
                            Position = "GK"
                        },
                        new
                        {
                            Id = 14,
                            Age = 30,
                            FirstName = "Carlos",
                            LastName = "Casemiro",
                            Position = "CDM"
                        },
                        new
                        {
                            Id = 15,
                            Age = 23,
                            FirstName = "Federico",
                            LastName = "Valverde",
                            Position = "CM"
                        },
                        new
                        {
                            Id = 16,
                            Age = 24,
                            FirstName = "Luka",
                            LastName = "Jovic",
                            Position = "CF"
                        },
                        new
                        {
                            Id = 17,
                            Age = 31,
                            FirstName = "Lucas",
                            LastName = "Vazquez",
                            Position = "RB"
                        },
                        new
                        {
                            Id = 18,
                            Age = 22,
                            FirstName = "Aurelien",
                            LastName = "Tchoumeni",
                            Position = "CDM"
                        },
                        new
                        {
                            Id = 19,
                            Age = 25,
                            FirstName = "Dani",
                            LastName = "Ceballos",
                            Position = "CM"
                        },
                        new
                        {
                            Id = 20,
                            Age = 21,
                            FirstName = "Vinicius",
                            LastName = "Junior",
                            Position = "LW"
                        },
                        new
                        {
                            Id = 21,
                            Age = 21,
                            FirstName = "Rodrygo",
                            LastName = "Goes",
                            Position = "RW"
                        },
                        new
                        {
                            Id = 22,
                            Age = 29,
                            FirstName = "Antonio",
                            LastName = "Rudiger",
                            Position = "CB"
                        },
                        new
                        {
                            Id = 23,
                            Age = 27,
                            FirstName = "Ferland",
                            LastName = "Mendy",
                            Position = "LB"
                        },
                        new
                        {
                            Id = 24,
                            Age = 28,
                            FirstName = "Mariano",
                            LastName = "Diaz",
                            Position = "CF"
                        },
                        new
                        {
                            Id = 25,
                            Age = 19,
                            FirstName = "Eduardo",
                            LastName = "Camavinga",
                            Position = "CM"
                        },
                        new
                        {
                            Id = 35,
                            Age = 20,
                            FirstName = "Miguel",
                            LastName = "Gutierrez",
                            Position = "LB"
                        });
                });

            modelBuilder.Entity("TrainingApp.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            TrainingId = 1,
                            Field = "B",
                            SessionDate = new DateTime(2022, 7, 5, 20, 31, 9, 592, DateTimeKind.Local).AddTicks(2281),
                            SessionEnd = "21:30",
                            SessionStart = "20:00"
                        },
                        new
                        {
                            TrainingId = 2,
                            Field = "B",
                            SessionDate = new DateTime(2022, 7, 7, 20, 31, 9, 592, DateTimeKind.Local).AddTicks(2281),
                            SessionEnd = "21:30",
                            SessionStart = "20:00"
                        },
                        new
                        {
                            TrainingId = 3,
                            Field = "B",
                            SessionDate = new DateTime(2022, 7, 9, 20, 31, 9, 592, DateTimeKind.Local).AddTicks(2281),
                            SessionEnd = "21:30",
                            SessionStart = "20:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
